# Default values for learn-kedro-service

# Deployment mode: 'job' for on-demand execution or 'deployment' for long-running service
mode: job

# Job specific configuration (used when mode is 'job')
job:
  # Time to keep completed jobs (in seconds)
  ttlSecondsAfterFinished: 100
  # Number of retries before considering a job as failed
  backoffLimit: 3

# Deployment specific configuration (used when mode is 'deployment')
replicaCount: 1

image:
  repository: kedro-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

# Enable SSH access (only used in deployment mode)
ssh:
  enabled: true
  port: 22

# Resource specifications as per requirements
resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 1
    memory: 4Gi

# Storage configuration
persistence:
  enabled: true
  size: 10Gi
  mountPath: /home/kedro_docker/data

# Pod security context
securityContext:
  runAsUser: 999
  runAsGroup: 0
  fsGroup: 0

# Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
