{{- if eq .Values.mode "deployment" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ssh.enabled }}
    - port: {{ .Values.ssh.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    {{- end }}
  selector:
    app: {{ .Release.Name }}
{{- end }}
