apiVersion: v2
name: learn-kedro-service
description: A Helm chart for deploying the Kedro application (supports both on-demand job and long-running deployment modes)
type: application
version: 0.2.0
appVersion: "1.0.0"
