name: Publish and share Kedro Viz

permissions:
    contents: write
    pages: write
    id-token: write

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch the repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11
            - name: Install Project Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Deploy Kedro-Viz to GH Pages
              uses: kedro-org/publish-kedro-viz@v2

# https://github.com/kedro-org/publish-kedro-viz?tab=readme-ov-file#prerequisites